# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3046415b16defb7f151e90dff3b10c743c48964c205f74873fb2b544fd3d5f0bf019922aceebce340cdcc04148430007196b0b2645e694da641803043c7bc057

test:
  secret_key_base: 510c8dcc79f5aa8b5d7f7b0e28b1799db9cd60b7dc0e10930765a672d17df717c0a461aea67050ee8d3a94a57c4e17f5ffec989740957afd3a90d1fb92f19169

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
